<?xml version="1.0" encoding="UTF-8"?>
<testsuite hostname="PC" name="pravin.TestWSTest" tests="2" failures="1" timestamp="24 Oct 2015 19:40:56 GMT" time="0.107" errors="0">
  <testcase name="testDateFunctionReturnsValidXML" time="0.092" classname="pravin.TestWSTest">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at pravin.TestWSTest.testDateFunctionReturnsValidXML(TestWSTest.java:46)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:70)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:109)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
... Removed 28 stack frames]]>
    </failure>
  </testcase>
  <testcase name="testDateFunctionReturnsValue" time="0.001" classname="pravin.TestWSTest"/>
</testsuite>
